#!/bin/sh
printf "\n"
USAGE="\n usage: terramon-ng <start|stop> <interface> [channel or frequency]\nArguments MUST be provided in that order.\n"
FUNCTION="$1"
INTERFACE="$2"
CHANFREQ="$3"

#Checking if help requested
if [ $FUNCTION -z ] || [ $FUNCTION -eq "--help" ]
  printf "$USAGE"
fi

if [ $FUNCTION -eq "start" ]
  if [ $INTERFACE -z ]
    printf "$USAGE"
  else
    if [ $CHANFREQ -z ]
      ip link set $INTERFACE down > /dev/null 2>&1
      iw dev $INTERFACE set type monitor > /dev/null 2>&1
      ip link set $INTERFACE up > /dev/null 2>&1
      
      iw dev $INTERFACE info
    else
      printf "Channel/Frequency switching not yet implemented"
    fi
  fi
elif [ $FUNCTION -eq "stop" ]
  if [ $INTERFACE -z ]
    printf "$USAGE"
  else
    if [ $CHANFREQ -z ]
      ip link set $INTERFACE down > /dev/null 2>&1
      iw dev $INTERFACE set type managed > /dev/null 2>&1
      ip link set $INTERFACE up > /dev/null 2>&1
      
      iw dev $INTERFACE info
    else
      printf "Channel/Frequency switching not yet implemented"
    fi
  fi
else
  printf "$USAGE"
fi

printf "\n"
